[package]
authors = ["Emerentius <Emerentius@arcor.de>"]
name = "sudoku-cli"
version = "0.4.1"
license = "AGPL-3.0"

[[bin]]
name = "sudoku"
path = "src/main.rs"

[dependencies]
clap = "2.32.0"
sudoku = { version = "0.6.2", features = ["unchecked_indexing"] }
rayon = "1.0.2"

[profile.release]
lto = true
codegen-units = 1
