[package]
authors = ["Emerentius <Emerentius@arcor.de>"]
name = "sudoku-cli"
version = "0.2.0"
license = "AGPL-3.0"

[[bin]]
name = "sudoku"
path = "src/main.rs"

[dependencies]
clap = "2.29"
isatty = "0.1.6"
sudoku = "0.4.1"

[dependencies.rayon]
optional = true
version = "0.9"

[features]
default = ["rayon"]
