[package]
authors = ["Emerentius <Emerentius@arcor.de>"]
name = "sudoku-cli"
version = "0.3.0"
license = "AGPL-3.0"

[[bin]]
name = "sudoku"
path = "src/main.rs"

[dependencies]
clap = "2.29"
sudoku = { version="0.5.0", features = ["unchecked_indexing"] }

[dependencies.rayon]
optional = true
version = "0.9"

[features]
default = ["rayon"]
