[package]
authors = ["Emerentius <Emerentius@arcor.de>"]
name = "sudoku-cli"
version = "0.4.1"
license = "AGPL-3.0"

[[bin]]
name = "sudoku"
path = "src/main.rs"

[dependencies]
clap = "2.32.0"
sudoku = { version = "0.6.2", features = ["unchecked_indexing"] }
rayon = "1.0.2"

[features]
# if this feature is activated, all parallelizable actions
# will use multiple threads by default
# That is, with this feature multithreading is used unless the --no-parallel flag is passed
# Otherwise a single thread is used unless --parallel is passed
parallel_by_default = []

[profile.release]
lto = true
codegen-units = 1
