[package]
authors = ["Emerentius <Emerentius@arcor.de>"]
name = "sudoku-cli"
version = "0.4.0"
license = "AGPL-3.0"

[[bin]]
name = "sudoku"
path = "src/main.rs"

[dependencies]
clap = "2.31.2"
sudoku = { version = "0.6.0", features = ["unchecked_indexing"] }

[dependencies.rayon]
optional = true
version = "1.0.1"

[features]
default = ["rayon"]

[profile.release]
lto = true
codegen-units = 1
